"""Add ticker_mappings table

Revision ID: 0fe97bf472da
Revises: 8f9c9587ff04
Create Date: 2026-02-01 15:17:43.362540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fe97bf472da'
down_revision: Union[str, None] = '8f9c9587ff04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'ticker_mappings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('ibkr_symbol', sa.String(length=20), nullable=False),
        sa.Column('ibkr_exchange', sa.String(length=20), nullable=False),
        sa.Column('ibkr_conid', sa.Integer(), nullable=True),
        sa.Column('yahoo_ticker', sa.String(length=20), nullable=False),
        sa.Column('source', sa.String(length=50), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('notes', sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('ibkr_symbol', 'ibkr_exchange', name='uq_ibkr_symbol_exchange')
    )
    op.create_index(op.f('ix_ticker_mappings_id'), 'ticker_mappings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticker_mappings_id'), table_name='ticker_mappings')
    op.drop_table('ticker_mappings')
    # ### end Alembic commands ###
