"""Initial migration - create all tables

Revision ID: 8f9c9587ff04
Revises: 
Create Date: 2026-01-31 18:38:30.923154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f9c9587ff04'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('from_currency', sa.String(length=3), nullable=False),
    sa.Column('to_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'from_currency', 'to_currency', name='uix_date_currencies')
    )
    op.create_index('ix_date_from_currency', 'exchange_rates', ['date', 'from_currency'], unique=False)
    op.create_index(op.f('ix_exchange_rates_date'), 'exchange_rates', ['date'], unique=False)
    op.create_index(op.f('ix_exchange_rates_id'), 'exchange_rates', ['id'], unique=False)
    op.create_table('securities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('conid', sa.Integer(), nullable=False),
    sa.Column('asset_category', sa.String(length=20), nullable=True),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin', 'exchange', name='uix_isin_exchange')
    )
    op.create_index(op.f('ix_securities_conid'), 'securities', ['conid'], unique=True)
    op.create_index(op.f('ix_securities_id'), 'securities', ['id'], unique=False)
    op.create_index(op.f('ix_securities_isin'), 'securities', ['isin'], unique=False)
    op.create_index('ix_symbol_currency', 'securities', ['symbol', 'currency'], unique=False)
    op.create_table('market_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id', 'date', name='uix_security_date')
    )
    op.create_index('ix_date_security', 'market_prices', ['date', 'security_id'], unique=False)
    op.create_index(op.f('ix_market_prices_date'), 'market_prices', ['date'], unique=False)
    op.create_index(op.f('ix_market_prices_id'), 'market_prices', ['id'], unique=False)
    op.create_index(op.f('ix_market_prices_security_id'), 'market_prices', ['security_id'], unique=False)
    op.create_table('taxlots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('open_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('cost_basis_eur', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_is_open', 'taxlots', ['is_open'], unique=False)
    op.create_index('ix_open_date_security', 'taxlots', ['open_date', 'security_id'], unique=False)
    op.create_index(op.f('ix_taxlots_id'), 'taxlots', ['id'], unique=False)
    op.create_index(op.f('ix_taxlots_open_date'), 'taxlots', ['open_date'], unique=False)
    op.create_index(op.f('ix_taxlots_security_id'), 'taxlots', ['security_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taxlots_security_id'), table_name='taxlots')
    op.drop_index(op.f('ix_taxlots_open_date'), table_name='taxlots')
    op.drop_index(op.f('ix_taxlots_id'), table_name='taxlots')
    op.drop_index('ix_open_date_security', table_name='taxlots')
    op.drop_index('ix_is_open', table_name='taxlots')
    op.drop_table('taxlots')
    op.drop_index(op.f('ix_market_prices_security_id'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_id'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_date'), table_name='market_prices')
    op.drop_index('ix_date_security', table_name='market_prices')
    op.drop_table('market_prices')
    op.drop_index('ix_symbol_currency', table_name='securities')
    op.drop_index(op.f('ix_securities_isin'), table_name='securities')
    op.drop_index(op.f('ix_securities_id'), table_name='securities')
    op.drop_index(op.f('ix_securities_conid'), table_name='securities')
    op.drop_table('securities')
    op.drop_index(op.f('ix_exchange_rates_id'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_date'), table_name='exchange_rates')
    op.drop_index('ix_date_from_currency', table_name='exchange_rates')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
